name: CI Tests & Allure Report

on:
  push:
    branches: [ "feature/allure-ci-report" ]  # Следим ТОЛЬКО за этой веткой, пока тестируем

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Сборка без тестов (чтобы проверить, что проект вообще собирается)
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Запуск тестов. Они должны упасть (это нормально для проверки скриншотов)
      - name: Run Tests & Generate Allure Results
        run: mvn test
        continue-on-error: true  # ВАЖНО: не останавливать пайплайн, если тесты красные

      # Генерация HTML-отчета из результатов
      - name: Generate Allure Report
        run: mvn allure:report
        continue-on-error: true

      # Публикация отчета на GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/site/allure-maven'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4